config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'
  get 'conversations/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create] 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, class_name: "User", foreign_key: "sender_id"
    belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
    #untuk menentukan id, jadi si pengirim dan penerima sehingga mudah dilacak/dicari

    has_many :messages, dependent: :destroy
    #dapat menerima banyak pesan

    validates_uniqueness_of :sender_id, scope: :receiver_id

    scope :between, -> (sender_id,receiver_id) do
        where("(conversations.sender_id = ? AND cOR (conversations.receiveonversations.receiver_id = ?) r_id = ? AND conversations.sender_id = ?)", sender_id, receiver_id, sender_id, receiver_id)
    end

    def recipient(current_user)    
      self.sender_id == current_user.id ? self.receiver : self.sender
    end

    def unread_message_count(current_user)
        self.messages.where("user_id != ? AND read = ?", current_user.id, false).count
    end
    
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :body, :conversation_id, :user_id

  private
    def message_time
      created_at.strftime("%d/%m/%y at %l:%M %p")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate
 
  def index
    @conversations = Conversation.where("sender_id = ? OR receiver_id = ?", current_user.id, current_user.id)
    @users = User.where.not(id: current_user.id)
  end

  def create
    if Conversation.between(params[:sender_id], params[:receiver_id]).present?
      @conversation = conversation.between(params[:sender_id], params[:receiver_id]).first      
    else
      @conversation = Conversation.create!(conversation_params)
    end

    redirect_to conversation_messages_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :receiver_id)
    end 
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate

  before_action do 
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    @messages.where("user_id != ? AND read = ?", current_user.id, false).update_all(read: true)
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    @message.user = current_user

    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end 
end

private 
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/conversations/index.html.erb
<h1>Inbox</h1>
<ul>
  <% @conversations.each do |conversation| %>
     <li>
      <%= link_to conversation.recipient(current_user).username, conversation_messages_path(conversation) %>
      <% if !conversation.unread_message_count(current_user).zero? %>
        (<%= conversation.unread_message_count(current_user) %>)
      <% end %>
      </li>
      
    <% recipient = conversation.sender_id == current_user.id ? conversation.receiver : conversation.sender %>
    
    <li>
    <%= link_to recipient.username, conversation_messages_path(conversation) %>
    </li>
  <% end %>
</ul>

<h2>Users</h2>
<ul>
  <% @Users.each do |user| %>
    <li><%= link_to user.username, conversations_path(sender_id: current_user.id, receiver_id: user.id), method: :post %></li> 
  <% end %>
</ul>

<ul>
  <% @messages.each do |message| %>
    <% if message.body %>
      <li>
        <h4><%= message.user.username %></h4>
        <p><%= message.body %></p>
      </li>
    <% end %>
  <% end %>
</ul>

<%= form_for [@conversation, @message] do |f| %>
  <div class="field">
    <%= f.text_area :body, placeholder: "Your message" %>
  </div>

  <%= f.submit "Send" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/index.html.erb
<h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p>